### ISSUE TITLE
Add support for types that require comparison with literal 0

### ISSUE THREAD

**Issue by horenmar** [cschreib/snatch#43]
The assertions in these two tests do not compile, even though they would compile outside the decomposing assertion macro

```cpp
#include <snatch/snatch.hpp>

TEST_CASE("spaceshippy", "[tag1][tag2]") {
    int a = 1, b = 1;
    REQUIRE(a <=> b == 0);
};

TEST_CASE("ptr", "[tag1][tag2]") {
    int* p = NULL;
    REQUIRE(p == NULL);
};
```

This is because both `std::ordering*` and `T*` are types that require comparisons with _literal_ 0, not just any `int` (or `long` in case of `NULL` on some platforms).

**Comment by cschreib** [comment]
Thank you for the bug report! I noticed _Catch2_ recently added support for this. 

I will separate the discussion for both tests:
1. `std::*_ordering` types. My initial reaction was that, this being a special case, it may best handled with a custom matcher. This would keep the code for the general case check macros simpler, and would avoid any regression in compilation time. However perhaps the cost is small. Apart from `T*` (which is discussed below), if the STL ordering types are the only types that can only be compared to literal 0, then we can get cheap automatic detection based on `std::is_convertible_v<T,std::partial_ordering>` to handle these special classes. I'll see if I can measure a performance hit with that.
2. _snatch_ being exclusively C++20, I don't intend to provide any support for comparison with `NULL`. Call me opinionated, but people should use `nullptr` :)

**Comment by horenmar** [comment]
1. Actually any type can be made comparable with 0 only*. Users can make types like this by using the same technique the stdlib orderings use, e.g.

```cpp
struct ZeroLiteralDetector {
    constexpr ZeroLiteralDetector( ZeroLiteralDetector* ) noexcept {}

    template <typename T,
              typename = std::enable_if_t<!std::is_same<T, int>::value>>
    constexpr ZeroLiteralDetector( T ) = delete;
};

struct TypeWithLit0Comparisons {
    friend bool operator==(TypeWithLit0Comparisons lhs, ZeroLiteralDetector) {
        return true;
    }
};
```

2. Eh, sure.

**Comment by cschreib** [comment]
Thanks, I did see this class in your implementation :) I would consider this as part of the "odd construct" list, namely, stuff that is legal C++ but rather niche, that few would use it, and even fewer have a good reason for it. This list contains things like type with non-const comparison operators, or comparisons that depend on implicit conversion chains from l-value references, etc.

I don't think it in is the scope of _snatch_ to support every and all corner cases; after all there are already good libraries that do that! I thought supporting the standard ordering types could be worth it, because, niche as they are, they are vocabulary types available in the standard. But I would definitely stop there, and not worry about user-defined classes with a similar behaviour.

Now I'm even considering whether we want to support the STL ordering types at all. There are good workarounds available, including using `a == b` instead of `a <=> b == 0`, or if one insists on comparing the ordering type, stuff like `a <=> b == std::strong_ordering::equal`.

The benchmarks I did seem to suggest the cost of supporting the STL types is very small (I couldn't measure any regression). But I worry about complexifying the code base. I'll think about it some more!

**Comment by cschreib** [comment]
I approached it from a different angle in https://github.com/cschreib/snatch/commit/fa1f860a854e36a65f9a8c6c11b2b090027d4128. Briefly: using concepts, _snatch_ will check at compile time if it is able to decompose the expression. If yes, it will do as it does today. If not, it will fallback to a simpler check that doesn't attempt to decompose the expression, and just reports when the check fails. 

I think this is nicer, because it doesn't requires us to add ad-hoc support for weird types. Common situations will benefit from the expression decomposer, and niche situations will not. But the checks will still compile, and report when fail. Using this approach, _snatch_ can now support checks like `REQUIRE(i == 1 && j == 2)`; it won't decompose them, but it will work.

I still have to check the performance impact though... :crossed_fingers:

**Comment by cschreib** [comment]
Benchmarks don't reveal any significant cost, so I will go with this approach. Thanks for raising the issue!
